import { Metadata } from 'next';
import LoginForm from '~/components/pages/Auth/LoginForm';

export const metadata: Metadata = {
  title: 'Login - FilmPub',
  description: 'Generated by create next app',
};

export default function LoginPage() {
  return <LoginForm />;
}
