import { Metadata } from 'next';
import RegisterForm from '~/components/Auth/RegisterForm';

export const metadata: Metadata = {
  title: 'Create new user - FilmPub',
  description: 'Generated by create next app',
};

export default function LoginPage() {
  return (
    <>
      <div className="fixed inset-0 z-0 h-full w-full bg-cover" style={{ backgroundImage: `url(/bg-login.jpg)` }}></div>
      <RegisterForm />
    </>
  );
}
