import { Metadata } from 'next';
import RegisterForm from '~/components/pages/Auth/RegisterForm';

export const metadata: Metadata = {
  title: 'Create new user - FilmPub',
  description: 'Generated by create next app',
};

export default function RegisterPage() {
  return <RegisterForm />;
}
