import type { Metadata } from 'next';
import '~/app/globals.css';
import Header from '~/layouts/header/Header';

export const metadata: Metadata = {
  title: 'Film Pub',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <main>
      <Header />
      {children}
    </main>
  );
}
