import type { Metadata } from 'next';
import { Footer, Header } from '~/layouts';

export const metadata: Metadata = {
  title: 'Film Pub',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <div className="flex min-h-screen flex-col">
      <Header />
      {children}
      <Footer />
    </div>
  );
}
