import type { Metadata } from 'next';
import '~/app/globals.css';

export const metadata: Metadata = {
  title: 'Film Pub',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return <div>{children}</div>;
}
